config:
  logging:
    file: ./logs/app.log
    level: DEBUG
  name: BW_limited
  outline:
    countries:
    - BW
    years:
    - 2030
    data_file_path: ./osemosys_data/input_data/TEMBA_SSP4-60.xlsx
    fuel_code_file_path: ./osemosys_data/fuelcodes(in).csv
    tech_code_file_path: ./osemosys_data/techcodes(in).csv
    representation_per_year: ['S1D1', 'S1D2', 'S2D1', 'S2D2', 'S3D1', 'S3D2', 'S4D1', 'S4D2'] # Representations inside an year
    timeout_time_step: 120
    max_iterations: 30
    delta_marginal_cost: 0.05
    marginal_cost_tolerance: 100 
    domains: 
      capacity: 
          min: 0
          max: 100000
          step: 200
      rateActivity: 
          min: 0
          max: 4000000
          step: 1000

    
  output_file_path: solutions/test-2030
