config:
  logging:
    file: ./logs/app.log
    level: DEBUG
  name: ZA_limited
  outline:
    countries:
    - ZA
    years:
    - 2030
    data_file_path: ./data/input_data/TEMBA_SSP4-60.xlsx
    fuel_code_file_path: ./data/fuelcodes(in).csv
    tech_code_file_path: ./data/techcodes(in).csv
    representation_per_year: 8 # Representations inside an year
    max_iterations: 30
    delta_marginal_cost: 0.05
  output_file_path: solutions/SAPP-single-country-limited-technology-2030
