config:
  logging:
    file: ./logs/app.log
    level: DEBUG
  name: ZA_limited
  outline:
    countries:
    - ZA
    data_file_path: ./data/input_data/TEMBA_SSP4-60.xlsx
    fuel_code_file_path: ./data/fuelcodes(in).csv
    tech_code_file_path: ./data/techcodes(in).csv
    year: 2030
  output_file_path: solutions/SAPP-single-country-limited-technology-2030/problems/ZA_limited_output.xml
