config:
  name: "Zambezi"

  logging:
    level: "DEBUG"
    file: "./logs/app.log"

  outline:
    countries: ['AO', 'BW', 'CD', 'LS', 'MW', 'MZ', 'NA', 'SZ', 'TZ', 'ZA', 'ZM', 'ZW']
    year: 2050
    file_path: '../../data/TEMBA_SSP1-26.xlsx'
  