config:
  name: "Zambezi"

  logging:
    level: "DEBUG"
    file: "./logs/app.log"

  outline:
    countries: ['ZM', 'ZW', 'MZ']
    year: 2050
    #scenario: "ssp5-2.6"
  
#TODO: this should become a database that links also to the information source
powerplants:
  Hydro_RunOfRiver:
    installation_cost_per_MW: 3000  # $/MW (Capital cost)
    operating_cost_per_MWh: 5       # $/MWh (Includes maintenance & operational costs)
    fuel_cost_per_MWh: 0            # $/MWh (No fuel cost for hydro)
    emissions:
      CO2: 0.0    # tCO2/MWh (Tons of CO2 per MWh)
      N2O: 0.0    # tN2O/MWh (Tons of N2O per MWh)
      CH4: 0.02   # tCH4/MWh (Tons of CH4 per MWh)
      CFCs: 0.0   # tCFC/MWh (Tons of CFCs per MWh)
    capacity_factor:
      mean: 45  # Fraction (Typical utilization rate)
    max_installable_capacity_MW:
      MZ: 4000  # MW
      ZM: 3000  # MW
      ZW: 2500   # MW

  Solar_PV:
    installation_cost_per_MW: 1000  # $/MW
    operating_cost_per_MWh: 10      # $/MWh
    fuel_cost_per_MWh: 0            # $/MWh
    emissions:
      CO2: 0.0    # tCO2/MWh
      N2O: 0.0    # tN2O/MWh
      CH4: 0.0    # tCH4/MWh
      CFCs: 0.0   # tCFC/MWh
    capacity_factor:
      mean: 22
    max_installable_capacity_MW:
      MZ: 10000
      ZM: 10000
      ZW: 10000

  Wind:
    installation_cost_per_MW: 1500  # $/MW
    operating_cost_per_MWh: 8       # $/MWh
    fuel_cost_per_MWh: 0            # $/MWh
    emissions:
      CO2: 0.0    # tCO2/MWh
      N2O: 0.0    # tN2O/MWh
      CH4: 0.0    # tCH4/MWh
      CFCs: 0.0   # tCFC/MWh
    capacity_factor:
      mean: 35
    max_installable_capacity_MW:
      MZ: 3000
      ZM: 2500
      ZW: 2000

  Waste:
    installation_cost_per_MW: 2500  # $/MW
    operating_cost_per_MWh: 20      # $/MWh
    fuel_cost_per_MWh: 5            # $/MWh
    emissions:
      CO2: 0.4    # tCO2/MWh
      N2O: 0.01   # tN2O/MWh
      CH4: 0.02   # tCH4/MWh
      CFCs: 0.01  # tCFC/MWh
    capacity_factor:
      mean: 55
    max_installable_capacity_MW:
      MZ: 500
      ZM: 400
      ZW: 300

  Nuclear:
    installation_cost_per_MW: 6000  # $/MW
    operating_cost_per_MWh: 15      # $/MWh
    fuel_cost_per_MWh: 5            # $/MWh
    emissions:
      CO2: 0.0    # tCO2/MWh
      N2O: 0.0    # tN2O/MWh
      CH4: 0.0    # tCH4/MWh
      CFCs: 0.0   # tCFC/MWh
    capacity_factor:
      mean: 85
    max_installable_capacity_MW:
      MZ: 1000
      ZM: 800
      ZW: 500

  Biomass:
    installation_cost_per_MW: 2500  # $/MW
    operating_cost_per_MWh: 18      # $/MWh
    fuel_cost_per_MWh: 10           # $/MWh
    emissions:
      CO2: 0.25   # tCO2/MWh
      N2O: 0.03   # tN2O/MWh
      CH4: 0.01   # tCH4/MWh
      CFCs: 0.0   # tCFC/MWh
    capacity_factor:
      mean: 65
    max_installable_capacity_MW:
      MZ: 1200
      ZM: 1000
      ZW: 800

  Bioenergy:
    installation_cost_per_MW: 2200  # $/MW
    operating_cost_per_MWh: 16      # $/MWh
    fuel_cost_per_MWh: 8            # $/MWh
    emissions:
      CO2: 0.2    # tCO2/MWh
      N2O: 0.02   # tN2O/MWh
      CH4: 0.02   # tCH4/MWh
      CFCs: 0.0   # tCFC/MWh
    capacity_factor:
      mean: 60
    max_installable_capacity_MW:
      MZ: 1400
      ZM: 1100
      ZW: 900

  Oil:
    installation_cost_per_MW: 1200  # $/MW
    operating_cost_per_MWh: 30      # $/MWh
    fuel_cost_per_MWh: 20           # $/MWh
    emissions:
      CO2: 0.7    # tCO2/MWh
      N2O: 0.02   # tN2O/MWh
      CH4: 0.02   # tCH4/MWh
      CFCs: 0.0   # tCFC/MWh
    capacity_factor:
      mean: 40
    max_installable_capacity_MW:
      MZ: 500
      ZM: 400
      ZW: 300

  HardCoal:
    installation_cost_per_MW: 1800  # $/MW
    operating_cost_per_MWh: 25      # $/MWh
    fuel_cost_per_MWh: 15           # $/MWh
    emissions:
      CO2: 0.9    # tCO2/MWh
      N2O: 0.04   # tN2O/MWh
      CH4: 0.03   # tCH4/MWh
      CFCs: 0.0   # tCFC/MWh
    capacity_factor:
      mean: 75
    max_installable_capacity_MW:
      MZ: 2000
      ZM: 1500
      ZW: 1000

  CCGT: #Natural Gas
    installation_cost_per_MW: 1100  # $/MW
    operating_cost_per_MWh: 12      # $/MWh
    fuel_cost_per_MWh: 6            # $/MWh
    emissions:
      CO2: 0.45   # tCO2/MWh
      N2O: 0.01   # tN2O/MWh
      CH4: 0.02   # tCH4/MWh
      CFCs: 0.0   # tCFC/MWh
    capacity_factor:
      mean: 60
    max_installable_capacity_MW:
      MZ: 2500
      ZM: 2000
      ZW: 1500
